<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rive</string>
	</array>
	<key>name</key>
	<string>Rivescript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#triggers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#replies</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#defines</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#labels</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#conditions</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>alternates</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\s\()([A-Za-z0-9\s\-]*)(\|)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>string.unquoted</string>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.alternates</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#characters</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>characters</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\,|\;|=|\|)</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>//.*$</string>
					<key>name</key>
					<string>comment.line.double-slash</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block</string>
				</dict>
			</array>
		</dict>
		<key>conditions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(\s*\*\s)(.+)(\s+(?:eq|ne|==|&lt;&gt;|&lt;=|&gt;=|&lt;|&gt;)\s+)(.+)(=&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>markup.raw</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>meta.condition</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tags</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\d+</string>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([A-Za-z0-9_]*)</string>
					<key>name</key>
					<string>constant.character</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\')(.*)(\')</string>
					<key>name</key>
					<string>string.quoted.single</string>
				</dict>
			</array>
		</dict>
		<key>defines</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(\s*\!\s(?:version|global|var|sub|person|array))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>string.unquoted</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>meta.define</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#characters</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>labels</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\s*[&lt;&gt;]\s+begin)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\s*[&lt;&gt;]\s+topic\s*)([A-Za-z0-9\\-_ ]*)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\s*[&lt;&gt;]\s+object\s+)(A-Za-z0-9\-_]+)?(\s+[A-Za-z0-9\-_]+)?</string>
				</dict>
			</array>
		</dict>
		<key>optionals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>constant.language</string>
					<key>match</key>
					<string>(\s\[)([A-Za-z0-9\s\-]*)(\])</string>
					<key>name</key>
					<string>meta.optionals</string>
				</dict>
			</array>
		</dict>
		<key>replies</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(\-)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>markup.raw</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>meta.reply</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#tags</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>tags</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&lt;|\{)(/?[A-Za-z0-9_]+)(.*?)(&gt;|\})</string>
					<key>name</key>
					<string>meta.tag</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&lt;|&gt;)</string>
				</dict>
			</array>
		</dict>
		<key>triggers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(\+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>string.unquoted</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>meta.trigger</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#alternates</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#optionals</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.rive</string>
	<key>uuid</key>
	<string>ca99ae33-dafb-4b98-b431-e1cfd5b2c46e</string>
</dict>
</plist>
